
services:
  discord-bot:
    build: .
    container_name: discord-bot-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WEB_PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge

volumes:
  logs:
